### ISSUE TITLE
Need Java 7 compiled BungeePerms for Legacy MC Versions

### ISSUE THREAD

**Issue by Zilacon** [weaondara/BungeePerms#343]
I currently have the BungeePerms running on my bungeecord which IS working on all my servers (1.5.2-1.13) however the server permissions are not being synced across servers. I am told to fix this i need to pur BungeePerms onto the server, however for servers like MCPC+ (1.5.2/1.6.4) these servers were programmed to be locked down to Java 7 only.

Can there be a Java 7 compiled version of BungeePerms to use on legacy servers?

**Comment by aurorasmiles** [comment]
You could compile BungeePerms yourself on Java 7, that should work

**Comment by Zilacon** [comment]
My developer @theresajayne says she cannot compile BungeePerms as it is missing dependencies.

**Comment by aurorasmiles** [comment]
https://img.cutiepie.at/sjgjecqdxbxjexqw
This is a Java7 version I just compiled, but I can't guarantee if it works or provide support for it.

**Comment by Zilacon** [comment]
Getting this error on start up:
```
07:36:02 [SEVERE] Error occurred while enabling BungeePerms v3.0 SNAPSHOT #1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()Ljava/util/Collection;
	at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin.getPlayers(BukkitPlugin.java:251)
	at net.alpenblock.bungeeperms.PermissionsManager.enable(PermissionsManager.java:154)
	at net.alpenblock.bungeeperms.BungeePerms.enable(BungeePerms.java:82)
	at net.alpenblock.bungeeperms.platform.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:88)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.loadPlugin(CraftServer.java:303)
	at org.bukkit.craftbukkit.v1_5_R3.CraftServer.enablePlugins(CraftServer.java:285)
	at cpw.mods.fml.common.event.FMLServerAboutToStartEvent.<init>(FMLServerAboutToStartEvent.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at cpw.mods.fml.common.LoaderState.getEvent(LoaderState.java:84)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:103)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:807)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:309)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:172)
	at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
```

**Comment by aurorasmiles** [comment]
It seems like some repos need to be updated, but in the meantime your dev and I figured something out.

**Comment by Zilacon** [comment]
Great! :D

**Comment by aurorasmiles** [comment]
https://github.com/weaondara/BungeePerms/issues/344
